# Generated by Django 2.2.5 on 2019-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0002_auto_20190929_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('PROBLEM', 'PROBLEM'), ('SUGGESTION', 'SUGGESTION'), ('OTHER', 'OTHER')], max_length=20),
        ),
    ]
