# Generated by Django 2.2.5 on 2019-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0003_auto_20190929_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userType',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='postedBy',
            new_name='posted_by',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='postedBy',
            new_name='posted_by',
        ),
    ]
