# Generated by Django 2.2.5 on 2019-09-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0005_event_facilitybooking_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_for_event', to='jiranapp.Event'),
        ),
    ]
