# Generated by Django 2.2.5 on 2019-09-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0006_auto_20190930_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='img_url',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
