# Generated by Django 2.2.5 on 2019-09-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0007_facility_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, verbose_name='Name of Account')),
                ('ic', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('invited_by', models.ForeignKey(on_delete=None, related_name='invited_by', to='jiranapp.Household')),
            ],
        ),
    ]
