# Generated by Django 2.2.5 on 2019-09-30 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0008_auto_20190930_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Visiting date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='date',
            field=models.DateField(verbose_name='Booking date'),
        ),
    ]
