# Generated by Django 2.2.5 on 2019-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0009_auto_20190930_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='Name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='Visitor Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(verbose_name='Visiting Date'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ic',
            field=models.CharField(default=11, max_length=20, verbose_name='Visitor IC No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(default=11, max_length=12, verbose_name='Visitor Contact'),
            preserve_default=False,
        ),
    ]
