# Generated by Django 2.2.5 on 2019-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0011_auto_20190930_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
    ]
