# Generated by Django 2.2.5 on 2019-09-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0012_eventinvitation_has_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hoseted_by_resident', to='jiranapp.Resident'),
            preserve_default=False,
        ),
    ]
