# Generated by Django 2.2.5 on 2019-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0013_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Event Name'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=None, related_name='payed_for_household', to='jiranapp.Household')),
            ],
        ),
        migrations.CreateModel(
            name='FeesCharged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=64)),
                ('date_charged', models.DateField()),
                ('due_date', models.DateField()),
                ('household', models.ForeignKey(on_delete=None, related_name='charged_to_household', to='jiranapp.Household')),
            ],
        ),
    ]
