# Generated by Django 2.2.5 on 2021-02-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0014_auto_20190930_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventinvitation',
            unique_together={('event', 'resident')},
        ),
    ]
