# Generated by Django 2.2.5 on 2021-02-07 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0015_auto_20210207_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(through='jiranapp.EventInvitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_invited_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
