# Generated by Django 2.2.5 on 2021-02-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiranapp', '0016_facilitybooking_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitybooking',
            unique_together={('facility', 'date')},
        ),
    ]
